- Repositories:
  - GitHub:
    - abbr: GH
      icon: github.png
      href: https://github.com/pontusc
  - Homelab:
    - abbr: HL
      icon: github.png
      href: https://github.com/pontusc/homelab
  - NVim:
    - abbr: NVim
      icon: github.png
      href: https://github.com/pontusc/nvim
  - Rekurrens:
    - abbr: GL
      icon: gitlab.png
      href: https://git.chasacademy.dev/chas-challenge-2025/group-12/rekurrens
