- Cluster Management:
  - Traefik:
      href: https://traefik.nejlikka.com
      siteMonitor: https://traefik.nejlikka.com
      icon: traefik.png
      description: Ingress
      # widget:
      #   type: traefik
      #   url: http://traefik.kube-system.svc.cluster.local:8080

  - ArgoCD:
      href: https://argocd.nejlikka.com
      siteMonitor: https://argocd.nejlikka.com
      icon: argo-cd.png
      description: Kubernetes GitOps

  - Rancher:
      href: https://rancher.nejlikka.com
      siteMonitor: https://rancher.nejlikka.com
      icon: rancher.png
      description: Kubernetes management

  - Longhorn:
      href: https://longhorn.nejlikka.com
      siteMonitor: https://longhorn.nejlikka.com
      icon: longhorn.png
      description: CSI Provider

  - Grafana:
      href: https://grafana.nejlikka.com
      siteMonitor: https://grafana.nejlikka.com
      icon: grafana.png
      description: Reports & Alerts

  - Authentik:
      href: https://authentik.nejlikka.com
      siteMonitor: https://authentik.nejlikka.com
      icon: authentik.png
      description: Authentication

  - Prometheus:
      href: https://prometheus.nejlikka.com
      siteMonitor: http://prometheus-server.monitoring.svc.cluster.local
      icon: prometheus.png
      description: Cluster logs
      widget:
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
