- Cluster Management:
  - Traefik:
      href: https://traefik.nejlikka.com
      siteMonitor: http://traefik.kube-system.svc.cluster.local:8080
      icon: traefik.png
      description: Ingress
      widget:
        type: traefik
        url: http://traefik.kube-system.svc.cluster.local:8080

  - Prometheus:
      href: https://prometheus.nejlikka.com
      siteMonitor: http://prometheus-server.monitoring.svc.cluster.local
      icon: prometheus.png
      description: Cluster logs
      widget:
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local

  - ArgoCD:
      href: https://argocd.nejlikka.com
      siteMonitor: http://argocd-server.argocd.svc.cluster.local:80
      icon: argo-cd.png
      description: Kubernetes GitOps
      widget:
        type: argocd
        url: http://argocd-server.argocd.svc.cluster.local:80
        key: "{{HOMEPAGE_VAR_ARGO_API_KEY}}"

  - Grafana:
      href: https://grafana.nejlikka.com
      siteMonitor: http://grafana.monitoring.svc.cluster.local:80
      icon: grafana.png
      description: Reports & Alerts
      widget:
        type: grafana
        url: http://grafana.monitoring.svc.cluster.local:80
        username: "admin"
        password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

  - Authentik:
      href: https://authentik.nejlikka.com
      siteMonitor: http://authentik-server.authentik.svc.cluster.local
      icon: authentik.png
      description: Authentication
      widget:
        type: authentik
        url: http://authentik-server.authentik.svc.cluster.local
        key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"

  - Uptime-kuma:
      href: https:///kuma.nejlikka.com
      siteMonitor: http://uptime-kuma.monitoring.svc.cluster.local:3001
      icon: uptime-kuma.png
      description: Service monitoring
      widget:
        type: uptimekuma
        url: http://uptime-kuma.monitoring.svc.cluster.local:3001
        slug: services

  - Longhorn:
      href: https://longhorn.nejlikka.com
      siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local
      icon: longhorn.png
      description: CSI Provider

  - Rancher:
      href: https://rancher.nejlikka.com
      siteMonitor: https://rancher.nejlikka.com
      icon: rancher.png
      description: Kubernetes management
