- Cluster Management:
  - Traefik:
      href: https://traefik.local.nejlikka.com
      siteMonitor: https://traefik.local.nejlikka.com
      icon: traefik.png
      description: Ingress
      widget:
        type: traefik
        url: https://traefik.local.nejlikka.com

  - Prometheus:
      href: https://prometheus.local.nejlikka.com
      siteMonitor: https://prometheus.local.nejlikka.com
      icon: prometheus.png
      description: Cluster logs
      widget:
        type: prometheus
        url: https://prometheus.local.nejlikka.com

  - ArgoCD:
      href: https://argocd.local.nejlikka.com
      siteMonitor: https://argocd.local.nejlikka.com
      icon: argo-cd.png
      description: Kubernetes GitOps

  - Rancher:
      href: https://rancher.local.nejlikka.com
      siteMonitor: https://grafana.local.nejlikka.com
      icon: rancher.png
      description: Kubernetes management

  - Longhorn:
      href: https://longhorn.local.nejlikka.com
      siteMonitor: https://longhorn.local.nejlikka.com
      icon: longhorn.png
      description: CSI Provider

  - Grafana:
      href: https://grafana.local.nejlikka.com
      siteMonitor: https://grafana.local.nejlikka.com
      icon: grafana.png
      description: Reports & Alerts

  - Authentik:
      href: https://authentik.local.nejlikka.com
      siteMonitor: https://authentik.local.nejlikka.com
      icon: authentik.png
      description: Authentication
