- kubernetes:
    cluster:
      show: false
      cpu: true
      memory: true
      showLabel: true
      label: "Cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
# - resources:
#     backend: resources
#     expanded: true
#     disk: /
#     cpu: true
#     memory: true
#     uptime: true
#     network: false
# - longhorn:
#     expanded: true
#     total: true
#     labels: true
#     nodes: true

- openmeteo:
    label: Stockholm # optional
    latitude: 59.3377
    longitude: 18.0900
    timezone: Europe/Stockholm # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
