name: Push manifests

"on":
  push:
    branches:
    - main

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      APP_PATH: homelab/deployments/homepage
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@vv4.0.0

    - name: Checkout homepage repo
      uses: actions/checkout@v4
      with:
        token: ${{secrets.PAT_TOKEN}}
        path: homepage

    - name: Checkout homelab repo
      uses: actions/checkout@v4
      with:
        repository: pontusc/homelab
        token: ${{secrets.PAT_TOKEN}}
        path: homelab

    - name: Generate manifest
      run: |
        kubectl create configmap homepage-config \
        --from-file=homepage/config/ \
        --dry-run=client -o yaml | \
        yq eval '.metadata.namespace = "homepage"' \
        > homepage/homepage-configmap.yml

    - name: Copy files
      run: |
        cp homepage/*.yml $APP_PATH

    - name: Commit files
      run: |
        cd homelab
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add deployments/homepage/*
        git commit -a -m "BOT: ${{github.event.head_commit.message}}" || exit 0

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        directory: homelab
        github_token: ${{secrets.PAT_TOKEN}}
        repository: pontusc/homelab
