name: Push manifests

"on":
  push:
    branches:
    - main

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      APP_PATH: homelab/apps/homepage
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@vv4.0.0

    - name: Checkout homepage repo
      uses: actions/checkout@v4
      with:
        token: ${{secrets.PAT_TOKEN}}
        path: homepage

    - name: Checkout homelab repo
      uses: actions/checkout@v4
      with:
        repository: pontusc/homelab
        token: ${{secrets.PAT_TOKEN}}
        path: homelab

    - name: Test filestructure
      run: ls

    - name: Generate manifest
      run: |
        kubectl create configmap homepage-config \
        --from-file=homepage/config/ \
        --dry-run=client -o yaml | > homepage/homepage-configmap.yml

        # for file in homepage/config/*; do
        #   # Remove path and suffix/filetype
        #   echo $file
        #   filename=$(basename "$file")
        #   filename=${filename%.*}
        #   kubectl create configmap "$filename" --from-file="$file" \
        #   --dry-run=client -o yaml > homepage/"$filename".yml
        # done

    - name: Copy files
      run: |
        cp homepage/*.yml $APP_PATH

    - name: Commit files
      run: |
        cd homelab
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add apps/homepage/*
        git commit -a -m "Push new manifests for homepage"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        directory: homelab
        github_token: ${{secrets.PAT_TOKEN}}
        repository: pontusc/homelab
